# Generated by Django 6.0 on 2026-01-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='amount_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='final_sanction_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
