# Generated by Django 6.0.1 on 2026-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_violation_amount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='severity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Zwaarte van deze overtreding (1-5). Laat leeg om de standaard zwaarte van het type te gebruiken.', null=True),
        ),
    ]
